#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# n8n Self-Hosted — Interactive Setup
# Generates .env files with secure random secrets.
# Works the same on-prem or cloud.
# =============================================================================

echo ""
echo "  n8n Self-Hosted Setup"
echo "  ====================="
echo ""

# Check for openssl
if ! command -v openssl &>/dev/null; then
  echo "Error: openssl is required but not installed."
  exit 1
fi

# --- TLS mode ---

echo "  How will you access this instance?"
echo ""
echo "    1) Domain name  (e.g. n8n.company.com) — automatic Let's Encrypt TLS"
echo "    2) IP address   (e.g. 192.168.1.50)    — self-signed TLS"
echo ""
read -rp "  Choose [1/2]: " TLS_CHOICE

case "$TLS_CHOICE" in
  1)
    TLS_MODE="letsencrypt"
    read -rp "  Domain name: " N8N_HOST
    if [[ -z "$N8N_HOST" ]]; then
      echo "Error: domain name is required."
      exit 1
    fi
    read -rp "  Email for Let's Encrypt notifications: " ACME_EMAIL
    if [[ -z "$ACME_EMAIL" ]]; then
      echo "Error: email is required for Let's Encrypt."
      exit 1
    fi
    TRAEFIK_RULE="Host(\`${N8N_HOST}\`)"
    N8N_PROTOCOL="https"
    ;;
  2)
    TLS_MODE="selfsigned"
    read -rp "  IP address or hostname (leave blank for localhost): " N8N_HOST
    N8N_HOST="${N8N_HOST:-localhost}"
    ACME_EMAIL=""
    TRAEFIK_RULE="PathPrefix(\`/\`)"
    N8N_PROTOCOL="https"
    ;;
  *)
    echo "Error: pick 1 or 2."
    exit 1
    ;;
esac

# --- Passwords ---

read -rp "  PostgreSQL password (leave blank to generate): " POSTGRES_PASSWORD
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-$(openssl rand -base64 24)}"

read -rp "  Grafana admin password (leave blank to generate): " GF_PASSWORD
GF_PASSWORD="${GF_PASSWORD:-$(openssl rand -base64 24)}"

# --- Generate secrets ---

N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
N8N_JWT_SECRET=$(openssl rand -hex 32)

# --- Write app .env ---

cat > .env <<EOF
# Generated by setup.sh on $(date +%Y-%m-%d)

# --- PostgreSQL ---
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=n8n

# --- N8N Security ---
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_JWT_SECRET=${N8N_JWT_SECRET}

# --- N8N Host ---
N8N_HOST=${N8N_HOST}
N8N_PROTOCOL=${N8N_PROTOCOL}

# --- TLS (${TLS_MODE}) ---
ACME_EMAIL=${ACME_EMAIL}
EOF

chmod 600 .env

# --- Generate Traefik dynamic config for domain mode ---
if [[ "$TLS_MODE" == "letsencrypt" ]]; then
  cat > config/traefik/dynamic.yml <<EOF
http:
  routers:
    n8n:
      rule: "Host(\`${N8N_HOST}\`)"
      entrypoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: n8n
      middlewares:
        - n8n-headers
        - n8n-ratelimit

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

  middlewares:
    n8n-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
    n8n-ratelimit:
      rateLimit:
        average: 100
        burst: 50
        period: "1m"
EOF
  echo "  Traefik config updated for Let's Encrypt"
fi

# --- Write monitoring .env ---

cat > monitoring/.env <<EOF
# Generated by setup.sh on $(date +%Y-%m-%d)

# --- Must match the app stack ---
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=n8n

# --- Grafana ---
GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
EOF

chmod 600 monitoring/.env

# --- Summary ---

echo ""
echo "  Done. Two .env files created (chmod 600)."
echo ""
echo "    .env              (app stack)"
echo "    monitoring/.env   (monitoring stack)"
echo ""
echo "  TLS mode: ${TLS_MODE}"
echo ""
echo "  Next steps:"
echo ""
echo "    1. docker compose up -d"
echo "    2. cd monitoring && docker compose up -d"

if [[ "$TLS_MODE" == "letsencrypt" ]]; then
  echo "    3. Visit https://${N8N_HOST}"
else
  if [[ "$N8N_HOST" == "localhost" ]]; then
    echo "    3. Visit https://localhost"
  else
    echo "    3. Visit https://${N8N_HOST}"
  fi
  echo ""
  echo "  Your browser will show a certificate warning. This is expected"
  echo "  with self-signed TLS. The encryption is the same."
fi

echo ""
echo "  Grafana: http://localhost:3000 (bound to localhost only)"
echo "    On a remote server, access via SSH tunnel:"
echo "      ssh -L 3000:localhost:3000 <your-server>"
echo "    user: admin"
echo "    pass: ${GF_PASSWORD}"
echo ""
