#!/usr/bin/env bash
# =============================================================================
# VM Bootstrap — runs once on first boot via GCP startup-script metadata.
# Installs Docker, clones the repo, generates secrets, and starts the stack.
#
# Expected metadata variables (set by provision-gcp.sh or GitHub Actions):
#   N8N_DOMAIN       — domain name, or empty for IP-only mode
#   ACME_EMAIL       — email for Let's Encrypt, required if N8N_DOMAIN is set
#   POSTGRES_PASS    — optional, auto-generated if blank
#   GRAFANA_PASS     — optional, auto-generated if blank
#   GH_REPO          — GitHub repo to clone (default: MarcusScipio/hardened-n8n-setup)
# =============================================================================
set -euo pipefail

LOG="/var/log/n8n-bootstrap.log"
exec > >(tee -a "$LOG") 2>&1
echo "[$(date)] Bootstrap started"

# --- Metadata helper ---
meta() {
  curl -sf -H "Metadata-Flavor: Google" \
    "http://metadata.google.internal/computeMetadata/v1/instance/attributes/$1" 2>/dev/null || echo ""
}

N8N_DOMAIN="$(meta n8n-domain)"
ACME_EMAIL="$(meta acme-email)"
POSTGRES_PASS="$(meta postgres-pass)"
GRAFANA_PASS="$(meta grafana-pass)"
GH_REPO="$(meta gh-repo)"
GH_REPO="${GH_REPO:-MarcusScipio/hardened-n8n-setup}"

# --- Install Docker (official method for Ubuntu/Debian) ---
if ! command -v docker &>/dev/null; then
  echo "[$(date)] Installing Docker..."
  apt-get update -y
  apt-get install -y ca-certificates curl gnupg
  install -m 0755 -d /etc/apt/keyrings
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | \
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  chmod a+r /etc/apt/keyrings/docker.gpg

  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
    https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
    > /etc/apt/sources.list.d/docker.list

  apt-get update -y
  apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
  systemctl enable docker
  systemctl start docker
  echo "[$(date)] Docker installed"
else
  echo "[$(date)] Docker already present"
fi

# --- Clone repo ---
DEPLOY_DIR="/opt/n8n"

if [[ -d "$DEPLOY_DIR/.git" ]]; then
  echo "[$(date)] Repo exists, pulling latest..."
  git -C "$DEPLOY_DIR" pull origin main
else
  echo "[$(date)] Cloning repo..."
  apt-get install -y git
  git clone "https://github.com/${GH_REPO}.git" "$DEPLOY_DIR"
fi

cd "$DEPLOY_DIR"

# --- Generate .env (non-interactive) ---
POSTGRES_PASS="${POSTGRES_PASS:-$(openssl rand -base64 24)}"
GRAFANA_PASS="${GRAFANA_PASS:-$(openssl rand -base64 24)}"
N8N_ENCRYPTION_KEY=$(openssl rand -hex 32)
N8N_JWT_SECRET=$(openssl rand -hex 32)

if [[ -n "$N8N_DOMAIN" ]]; then
  N8N_HOST="$N8N_DOMAIN"
  N8N_PROTOCOL="https"
else
  EXTERNAL_IP=$(curl -sf -H "Metadata-Flavor: Google" \
    http://metadata.google.internal/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip)
  N8N_HOST="${EXTERNAL_IP}"
  N8N_PROTOCOL="https"
  ACME_EMAIL=""
fi

cat > .env <<EOF
# Generated by bootstrap.sh on $(date +%Y-%m-%d)
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${POSTGRES_PASS}
POSTGRES_DB=n8n
N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
N8N_JWT_SECRET=${N8N_JWT_SECRET}
N8N_HOST=${N8N_HOST}
N8N_PROTOCOL=${N8N_PROTOCOL}
ACME_EMAIL=${ACME_EMAIL}
EOF
chmod 600 .env

# --- Generate Traefik dynamic config ---
if [[ -n "$N8N_DOMAIN" ]]; then
  cat > config/traefik/dynamic.yml <<EOF
http:
  routers:
    n8n:
      rule: "Host(\`${N8N_DOMAIN}\`)"
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
      service: n8n
      middlewares:
        - n8n-headers
        - n8n-ratelimit

  services:
    n8n:
      loadBalancer:
        servers:
          - url: "http://n8n:5678"

  middlewares:
    n8n-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        forceSTSHeader: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"
        permissionsPolicy: "camera=(), microphone=(), geolocation=()"
    n8n-ratelimit:
      rateLimit:
        average: 100
        burst: 50
        period: "1m"
EOF
  echo "[$(date)] Domain mode: Traefik config with Let's Encrypt"
else
  echo "[$(date)] IP mode: using default Traefik config (self-signed)"
fi

cat > monitoring/.env <<EOF
# Generated by bootstrap.sh on $(date +%Y-%m-%d)
POSTGRES_USER=n8n
POSTGRES_PASSWORD=${POSTGRES_PASS}
POSTGRES_DB=n8n
GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
EOF
chmod 600 monitoring/.env

echo "[$(date)] .env files generated"

# --- Start the stacks ---
echo "[$(date)] Starting app stack..."
docker compose up -d

echo "[$(date)] Starting monitoring stack..."
docker compose -f monitoring/docker-compose.yml up -d

echo "[$(date)] Bootstrap complete"
echo ""
echo "  n8n:     https://${N8N_HOST}"
echo ""
echo "  Grafana: localhost only (not publicly exposed)"
echo "    Access via SSH tunnel:"
echo "      gcloud compute ssh n8n-server --zone=<ZONE> --tunnel-through-iap -- -L 3000:localhost:3000"
echo "      Then open: http://localhost:3000"
echo "    Credentials: admin / ${GRAFANA_PASS}"
echo ""
echo "  All credentials saved to ${DEPLOY_DIR}/.env and ${DEPLOY_DIR}/monitoring/.env"
